BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Baggage';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CrewAssignment';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE UserSessions';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Payments';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Tickets';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Bookings';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AircraftSeats';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Flights';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Aircraft';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Passengers';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Users';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Airports';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE Airports (
    AirportCode VARCHAR2(3) PRIMARY KEY,
    AirportName VARCHAR2(100) NOT NULL,
    City VARCHAR2(50) NOT NULL,
    Country VARCHAR2(50) NOT NULL
);

CREATE INDEX idx_airports_city ON Airports(City);

CREATE TABLE Aircraft (
    AircraftID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Model VARCHAR2(50) NOT NULL,
    TailNumber VARCHAR2(20) NOT NULL UNIQUE,
    TotalSeats NUMBER(10) NOT NULL,
    ManufactureYear NUMBER(4)
);

CREATE INDEX idx_aircraft_tailnumber ON Aircraft(TailNumber);

CREATE TABLE Users (
    UserID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR2(255) NOT NULL,
    Role VARCHAR2(20) DEFAULT 'Passenger' 
        CHECK (Role IN ('Admin', 'Staff', 'Passenger')),
    CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_users_email ON Users(Email);
CREATE INDEX idx_users_role ON Users(Role);

CREATE TABLE Passengers (
    PassengerID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER(10) UNIQUE,
    PassportNumber VARCHAR2(20) NOT NULL UNIQUE,
    Nationality VARCHAR2(50),
    PhoneNumber VARCHAR2(20),
    FrequentFlyerNumber VARCHAR2(50) UNIQUE,
    CONSTRAINT fk_passengers_users 
        FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE SET NULL
);

CREATE INDEX idx_passengers_userid ON Passengers(UserID);
CREATE INDEX idx_passengers_passport ON Passengers(PassportNumber);

CREATE TABLE Flights (
    FlightID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FlightNumber VARCHAR2(10) NOT NULL UNIQUE,
    AircraftID NUMBER(10) NOT NULL,
    DepartureAirport VARCHAR2(3) NOT NULL,
    ArrivalAirport VARCHAR2(3) NOT NULL,
    DepartureTime TIMESTAMP NOT NULL,
    ArrivalTime TIMESTAMP NOT NULL,
    BasePrice NUMBER(10,2) NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Scheduled' 
        CHECK (Status IN ('Scheduled', 'Delayed', 'Departed', 'Arrived', 'Cancelled')),
    CONSTRAINT fk_flights_aircraft 
        FOREIGN KEY (AircraftID) REFERENCES Aircraft(AircraftID),
    CONSTRAINT fk_flights_departure_airport 
        FOREIGN KEY (DepartureAirport) REFERENCES Airports(AirportCode),
    CONSTRAINT fk_flights_arrival_airport 
        FOREIGN KEY (ArrivalAirport) REFERENCES Airports(AirportCode)
);

CREATE INDEX idx_flights_number ON Flights(FlightNumber);
CREATE INDEX idx_flights_aircraft ON Flights(AircraftID);
CREATE INDEX idx_flights_departure_time ON Flights(DepartureTime);
CREATE INDEX idx_flights_status ON Flights(Status);

CREATE TABLE AircraftSeats (
    SeatID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AircraftID NUMBER(10) NOT NULL,
    SeatNumber VARCHAR2(5) NOT NULL,
    Class VARCHAR2(20) NOT NULL 
        CHECK (Class IN ('Economy', 'Premium Economy', 'Business', 'First')),
    Status VARCHAR2(20) DEFAULT 'AVAILABLE' 
        CHECK (Status IN ('AVAILABLE', 'OCCUPIED', 'MAINTENANCE')),
    CONSTRAINT fk_aircraftseats_aircraft 
        FOREIGN KEY (AircraftID) REFERENCES Aircraft(AircraftID) ON DELETE CASCADE,
    CONSTRAINT uk_aircraftseats_seat 
        UNIQUE (AircraftID, SeatNumber)
);

CREATE INDEX idx_aircraftseats_aircraft ON AircraftSeats(AircraftID);
CREATE INDEX idx_aircraftseats_status ON AircraftSeats(Status);

CREATE TABLE Bookings (
    BookingID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingReference VARCHAR2(6) NOT NULL UNIQUE,
    UserID NUMBER(10),
    BookingDate TIMESTAMP DEFAULT SYSTIMESTAMP,
    Status VARCHAR2(20) DEFAULT 'Pending' 
        CHECK (Status IN ('Confirmed', 'Pending', 'Cancelled')),
    CONSTRAINT fk_bookings_users 
        FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE INDEX idx_bookings_reference ON Bookings(BookingReference);
CREATE INDEX idx_bookings_userid ON Bookings(UserID);
CREATE INDEX idx_bookings_status ON Bookings(Status);

CREATE TABLE Tickets (
    TicketID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingID NUMBER(10) NOT NULL,
    FlightID NUMBER(10) NOT NULL,
    PassengerID NUMBER(10) NOT NULL,
    SeatNumber VARCHAR2(5) NOT NULL,
    Class VARCHAR2(20) NOT NULL 
        CHECK (Class IN ('Economy', 'Premium Economy', 'Business', 'First')),
    TicketPrice NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_tickets_booking 
        FOREIGN KEY (BookingID) REFERENCES Bookings(BookingID) ON DELETE CASCADE,
    CONSTRAINT fk_tickets_flight 
        FOREIGN KEY (FlightID) REFERENCES Flights(FlightID),
    CONSTRAINT fk_tickets_passenger 
        FOREIGN KEY (PassengerID) REFERENCES Passengers(PassengerID),
    CONSTRAINT uk_tickets_seat 
        UNIQUE (FlightID, SeatNumber)
);

CREATE INDEX idx_tickets_booking ON Tickets(BookingID);
CREATE INDEX idx_tickets_flight ON Tickets(FlightID);
CREATE INDEX idx_tickets_passenger ON Tickets(PassengerID);

CREATE TABLE Payments (
    PaymentID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingID NUMBER(10) NOT NULL,
    Amount NUMBER(10,2) NOT NULL,
    PaymentDate TIMESTAMP DEFAULT SYSTIMESTAMP,
    PaymentMethod VARCHAR2(20) NOT NULL 
        CHECK (PaymentMethod IN ('Credit Card', 'Debit Card', 'PayPal', 'Stripe')),
    TransactionStatus VARCHAR2(20) NOT NULL 
        CHECK (TransactionStatus IN ('Success', 'Failed', 'Refunded')),
    TransactionReference VARCHAR2(100) UNIQUE,
    CONSTRAINT fk_payments_booking 
        FOREIGN KEY (BookingID) REFERENCES Bookings(BookingID)
);

CREATE INDEX idx_payments_booking ON Payments(BookingID);
CREATE INDEX idx_payments_status ON Payments(TransactionStatus);

CREATE TABLE UserSessions (
    SessionID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER(10) NOT NULL,
    RefreshToken VARCHAR2(500) NOT NULL,
    ExpiresAt TIMESTAMP NOT NULL,
    CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_usersessions_users 
        FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE INDEX idx_usersessions_userid ON UserSessions(UserID);

CREATE TABLE CrewAssignment (
    AssignmentID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FlightID NUMBER(10) NOT NULL,
    UserID NUMBER(10) NOT NULL,
    CrewRole VARCHAR2(50) NOT NULL 
        CHECK (CrewRole IN ('Pilot', 'Co-Pilot', 'Cabin Crew Lead', 'Cabin Crew')),
    CONSTRAINT fk_crewassignment_flight 
        FOREIGN KEY (FlightID) REFERENCES Flights(FlightID) ON DELETE CASCADE,
    CONSTRAINT fk_crewassignment_users 
        FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE INDEX idx_crewassignment_flight ON CrewAssignment(FlightID);
CREATE INDEX idx_crewassignment_user ON CrewAssignment(UserID);

CREATE TABLE Baggage (
    BaggageID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketID NUMBER(10) NOT NULL,
    WeightKG NUMBER(5,2) NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Checked-In' 
        CHECK (Status IN ('Checked-In', 'In-Transit', 'On-Plane', 'Ready-for-Pickup', 'Lost')),
    TrackingNumber VARCHAR2(50) NOT NULL UNIQUE,
    CONSTRAINT fk_baggage_ticket 
        FOREIGN KEY (TicketID) REFERENCES Tickets(TicketID) ON DELETE CASCADE
);

CREATE INDEX idx_baggage_ticket ON Baggage(TicketID);
CREATE INDEX idx_baggage_tracking ON Baggage(TrackingNumber);
CREATE INDEX idx_baggage_status ON Baggage(Status);

-- Performance & Composite Indexes
CREATE INDEX idx_flights_search ON Flights(DepartureAirport, ArrivalAirport, DepartureTime, Status);
CREATE INDEX idx_seats_aircraft_class ON AircraftSeats(AircraftID, Class, Status);
CREATE INDEX idx_bookings_date ON Bookings(BookingDate);
CREATE INDEX idx_payments_booking_status ON Payments(BookingID, TransactionStatus);
CREATE INDEX idx_airports_name ON Airports(AirportName);

INSERT INTO Airports (AirportCode, AirportName, City, Country) 
VALUES ('JFK', 'John F. Kennedy International', 'New York', 'USA');

INSERT INTO Airports (AirportCode, AirportName, City, Country) 
VALUES ('LAX', 'Los Angeles International', 'Los Angeles', 'USA');

INSERT INTO Airports (AirportCode, AirportName, City, Country) 
VALUES ('LHR', 'London Heathrow', 'London', 'UK');

INSERT INTO Airports (AirportCode, AirportName, City, Country) 
VALUES ('CDG', 'Paris Charles de Gaulle', 'Paris', 'France');

INSERT INTO Airports (AirportCode, AirportName, City, Country) 
VALUES ('NRT', 'Narita International', 'Tokyo', 'Japan');

INSERT INTO Airports (AirportCode, AirportName, City, Country) 
VALUES ('SYD', 'Sydney Kingsford Smith', 'Sydney', 'Australia');

INSERT INTO Airports (AirportCode, AirportName, City, Country) 
VALUES ('DXB', 'Dubai International', 'Dubai', 'UAE');

INSERT INTO Aircraft (Model, TailNumber, TotalSeats, ManufactureYear) 
VALUES ('Boeing 777-300ER', 'N1001A', 396, 2015);

INSERT INTO Aircraft (Model, TailNumber, TotalSeats, ManufactureYear) 
VALUES ('Boeing 787-9 Dreamliner', 'N2002B', 288, 2018);

INSERT INTO Aircraft (Model, TailNumber, TotalSeats, ManufactureYear) 
VALUES ('Airbus A350-900', 'N3003C', 325, 2017);

INSERT INTO Aircraft (Model, TailNumber, TotalSeats, ManufactureYear) 
VALUES ('Airbus A380-800', 'N4004D', 555, 2016);

INSERT INTO Flights (FlightNumber, AircraftID, DepartureAirport, ArrivalAirport, DepartureTime, ArrivalTime, BasePrice, Status)
VALUES ('AA101', 1, 'JFK', 'LAX', TIMESTAMP '2024-12-20 08:00:00', TIMESTAMP '2024-12-20 11:30:00', 450.00, 'Scheduled');

INSERT INTO Flights (FlightNumber, AircraftID, DepartureAirport, ArrivalAirport, DepartureTime, ArrivalTime, BasePrice, Status)
VALUES ('BA102', 2, 'LHR', 'JFK', TIMESTAMP '2024-12-20 10:00:00', TIMESTAMP '2024-12-20 13:00:00', 550.00, 'Scheduled');

INSERT INTO Flights (FlightNumber, AircraftID, DepartureAirport, ArrivalAirport, DepartureTime, ArrivalTime, BasePrice, Status)
VALUES ('AF103', 3, 'CDG', 'LAX', TIMESTAMP '2024-12-21 09:00:00', TIMESTAMP '2024-12-21 13:00:00', 650.00, 'Scheduled');

INSERT INTO Flights (FlightNumber, AircraftID, DepartureAirport, ArrivalAirport, DepartureTime, ArrivalTime, BasePrice, Status)
VALUES ('EK104', 4, 'DXB', 'SYD', TIMESTAMP '2024-12-22 15:00:00', TIMESTAMP '2024-12-23 07:00:00', 800.00, 'Scheduled');

INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'A1', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'A2', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'A3', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'A4', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'A5', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'A6', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'A7', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'A8', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'B1', 'Premium Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'B2', 'Premium Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'B3', 'Premium Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'B4', 'Business', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'B5', 'Business', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'B6', 'Business', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'F1', 'First', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (1, 'F2', 'First', 'AVAILABLE');

INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (2, 'A1', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (2, 'A2', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (2, 'A3', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (2, 'B1', 'Business', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (2, 'B2', 'Business', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (2, 'F1', 'First', 'AVAILABLE');

INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (3, 'A1', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (3, 'A2', 'Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (3, 'A3', 'Premium Economy', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (3, 'A4', 'Business', 'AVAILABLE');
INSERT INTO AircraftSeats (AircraftID, SeatNumber, Class, Status) VALUES (3, 'F1', 'First', 'AVAILABLE');

INSERT INTO Users (FirstName, LastName, Email, PasswordHash, Role) 
VALUES ('John', 'Doe', 'john@example.com', '$2b$10$example.hash.1', 'Passenger');

INSERT INTO Users (FirstName, LastName, Email, PasswordHash, Role) 
VALUES ('Jane', 'Smith', 'jane@example.com', '$2b$10$example.hash.2', 'Passenger');

INSERT INTO Users (FirstName, LastName, Email, PasswordHash, Role) 
VALUES ('Admin', 'User', 'admin@example.com', '$2b$10$example.hash.3', 'Admin');

INSERT INTO Users (FirstName, LastName, Email, PasswordHash, Role) 
VALUES ('Staff', 'Member', 'staff@example.com', '$2b$10$example.hash.4', 'Staff');

INSERT INTO Passengers (UserID, PassportNumber, Nationality, PhoneNumber, FrequentFlyerNumber)
VALUES (1, 'US123456', 'USA', '555-1234', 'AA1000001');

INSERT INTO Passengers (UserID, PassportNumber, Nationality, PhoneNumber, FrequentFlyerNumber)
VALUES (2, 'US789012', 'USA', '555-5678', 'AA1000002');

INSERT INTO Bookings (BookingReference, UserID, Status)
VALUES ('ABC123', 1, 'Confirmed');

INSERT INTO Tickets (BookingID, FlightID, PassengerID, SeatNumber, Class, TicketPrice)
VALUES (1, 1, 1, 'A1', 'Economy', 450.00);

INSERT INTO Payments (BookingID, Amount, PaymentMethod, TransactionStatus, TransactionReference)
VALUES (1, 450.00, 'Credit Card', 'Success', 'TXN001');

INSERT INTO CrewAssignment (FlightID, UserID, CrewRole)
VALUES (1, 4, 'Pilot');

INSERT INTO CrewAssignment (FlightID, UserID, CrewRole)
VALUES (1, 4, 'Cabin Crew Lead');

INSERT INTO Baggage (TicketID, WeightKG, Status, TrackingNumber)
VALUES (1, 23.5, 'Checked-In', 'BAG001');

COMMIT;

SELECT 'Airports' as TableName, COUNT(*) as RecordCount FROM Airports
UNION ALL
SELECT 'Aircraft', COUNT(*) FROM Aircraft
UNION ALL
SELECT 'Users', COUNT(*) FROM Users
UNION ALL
SELECT 'Passengers', COUNT(*) FROM Passengers
UNION ALL
SELECT 'Flights', COUNT(*) FROM Flights
UNION ALL
SELECT 'AircraftSeats', COUNT(*) FROM AircraftSeats
UNION ALL
SELECT 'Bookings', COUNT(*) FROM Bookings
UNION ALL
SELECT 'Tickets', COUNT(*) FROM Tickets
UNION ALL
SELECT 'Payments', COUNT(*) FROM Payments
UNION ALL
SELECT 'UserSessions', COUNT(*) FROM UserSessions
UNION ALL
SELECT 'CrewAssignment', COUNT(*) FROM CrewAssignment
UNION ALL
SELECT 'Baggage', COUNT(*) FROM Baggage;